

name: main

on:
  push:
    branches:
      - main 
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  

      - name: Install dependencies
        run: npm install

      - name: Run Jest tests
        run: npm test  

      - name: Reemplazar valores en el archivo .env
        run: |
          sed -i "s/^HOST=.*/HOST=${{ secrets.HOST }}/" .env
          sed -i "s|^PORT1=.*|PORT1=${{ secrets.PORT1 }}|" .env
          sed -i "s|^USER=.*|USER=${{ secrets.USER }}|" .env
          sed -i "s|^PASSWORD=.*|PASSWORD=${{ secrets.PASSWORD }}|" .env


      - name: Install Docker and Docker Compose
        run: |
          sudo apt-get update
          if ! command -v docker &> /dev/null; then
            echo "Docker no encontrado. Instalando..."
            sudo apt-get install -y docker.io
          else
            echo "Docker ya est치 instalado."
          fi

          if ! command -v docker-compose &> /dev/null; then
            echo "Docker Compose no encontrado. Instalando..."
            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
          else
            echo "Docker Compose ya est치 instalado."
          fi

          docker --version
          docker-compose --version

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images with Docker Compose
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push
          # Verificar que las im치genes se enviaron correctamente
          echo "Verificando im치genes enviadas a DockerHub:"
          docker-compose -f docker-compose.yml images